import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";

import { AuroraBackground } from "@/components/AuroraBackground";
import { Navigation } from "@/components/Navigation";
import { Player } from "@/components/Player";
import { Toaster } from "sonner";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`dark ${geistSans.variable} ${geistMono.variable} h-full`}
    >
      <body className="relative min-h-full flex flex-col bg-background text-foreground font-sans antialiased">
        <AuroraBackground />
        <Navigation />
        <Player />
        <Toaster theme="dark" position="bottom-center" richColors />
        <div className="relative z-10 flex min-h-0 flex-1 flex-col pb-[var(--wam-player-pad,0px)]">
          {children}
        </div>
      </body>
    </html>
  );
}
